# NumPy Functions:

In [1]:
# so to create a heading write a comment in python and then from selector choose heading not code mode and then execute 
# that cell

In [2]:
import numpy as np

# arange()

In [3]:
# sytax for arange is: np.arange(start, end, steps)
arr_1d = np.arange(1,13)
print(arr_1d) # this will print the array with element from 1 to 12 , 13 is exclusive here

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
# creating of even array
even_array = np.arange(1, 13, 2)
print(even_array)

[ 1  3  5  7  9 11]


# linspace()

In [6]:
# it will print element in defined range with equal space(difference)
np.linspace(1,5,4) # it will print the element of array in range of 1 to 5, with equal space

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [7]:
# it will reshape the array, that means suppose i have 1d array and i want to convert it into 2d array then we can do that by 
# using reshape function, here i have arr_1d array with 12 elements now let me convert it into 2x6
arr_2d = arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
# now let me convert it into 3d array
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [10]:
# it convert multidimensional array into 1d array
# see in above cell ar is 2 dimension array, now let me convert it into 1d
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [13]:
# Return a copy of the array collapsed into one dimension,
# that means we can collapsed the muti dimesion array by row and column
# for row order = 'C', and for column, order = 'F'
ar.flatten(order='F')

array([ 1,  7,  2,  8,  3,  9,  4, 10,  5, 11,  6, 12])

In [14]:
# see in ar array 1 and 7 in one column, 2 and 8 in second column, 3 and 9 in third column, 4 and 10 in fourth column,
# 5 and 11 in fiveth column, 6 and 12 and sixth column
# and finally they all are collapsed in 1d array

# transpose()

In [15]:
# it will traspose the matrix
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [17]:
# see ar was 2x6 matrix, and its transpose is now 6x2
# instead of using transpose() we can also use .T to get transpose of the matrix
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])