# Random Sampling with NumPy

In [2]:
import numpy as np
import random

In [18]:
random.choice([1,2,3,4,5,6])

1

In [23]:
np.random.random(1) # when ever you will use random.random then it will give the value from 0 to 1 (always),
# here i have pass 1 for number of elements that i want

array([0.84992623])

In [25]:
np.random.random(2) # here i have pass 2, means i will get two elements of array which value will be from 0 to 1

array([0.74680011, 0.91575323])

In [26]:
# now lets create the 2d array with random.random
np.random.random((3,3)) # so here i have to pass tuple of (row, column) for creating the array, 
# the value of element of array will lies between 0 to 1, because i have use random.random

array([[0.17776073, 0.54702261, 0.86167257],
       [0.44866857, 0.73289179, 0.60049826],
       [0.17372176, 0.37370148, 0.15777547]])

In [43]:
np.random.randint(1,4) # here i will get the single integer random value from 1 to 3, excluding 4

1

In [45]:
# now i want to create 2d matrix using randint
np.random.randint(1,4, (4,4)) # here 1,4 is the range and tuple(4,4) is the shape of the array

array([[1, 3, 3, 1],
       [1, 1, 3, 3],
       [1, 2, 2, 3],
       [1, 3, 1, 1]])

In [47]:
# lets create a nd array
# so here let me create the 3d array
np.random.randint(1, 4, (2,4,4)) # so here 4x4 array is creating 2 times , it representing 3d array

array([[[1, 3, 1, 3],
        [3, 3, 3, 1],
        [3, 2, 1, 2],
        [3, 3, 3, 3]],

       [[2, 2, 2, 1],
        [2, 3, 1, 2],
        [3, 1, 3, 3],
        [2, 1, 3, 1]]])

In [48]:
# suppose i have create a array using random.randint() and i want to use the same array later,
# does it possibe? because all the random.rand() create the new array, but yes it is possible using seed() function
np.random.seed(10)
np.random.randint(1, 4, (2, 4, 4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [50]:
# if i want to use the above array again, then write the same syntax
np.random.seed(10)
np.random.randint(1, 4, (2, 4, 4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [ ]:
# see above, both created array are same, if we will not use seed() then all the time it will create the different array

In [53]:
np.random.rand(3)

array([0.10540183, 0.28357668, 0.06556327])

In [54]:
# creating 2d array
np.random.rand(3,3)

array([[0.05644419, 0.76545582, 0.01178803],
       [0.61194334, 0.33188226, 0.55964837],
       [0.33549965, 0.41118255, 0.0768555 ]])

In [64]:
# creating 2d array
np.random.randn(3,3) # it create the array with the random negative and positive element

array([[ 0.25922513,  1.05800516, -0.09178444],
       [-0.72403459, -0.40046036,  0.44532458],
       [ 0.95993965, -1.34635384,  2.01889937]])

In [65]:
x = [1,2,3,4]
np.random.choice(x)

2

In [66]:
# lets create the permutation of list
np.random.permutation(x)

array([4, 3, 1, 2])

In [67]:
np.random.permutation(x)

array([1, 4, 2, 3])

In [68]:
# so here i have observe that np.random.permutation() actually shuffle the element all the time,
# so we can also use shuffle instead of permutation