# Python NumPy Array slicing(:)

In [1]:
import numpy as np

In [2]:
matrix = np.arange(1,101).reshape(10,10)
print(matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [3]:
matrix[0,0] # 0th row and 0th column value

1

In [4]:
matrix[0,0].ndim # its dimension is 0 because it is scalar

0

In [7]:
print(matrix[0]) # it will give the value of 0th row and its dimension will be 1d
print(matrix[0].ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [8]:
matrix[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [9]:
matrix[:,0] #slicing all rows and 0th column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [11]:
matrix[0,:] #s licing all column and 0th rows

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
matrix[2:]

array([[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [14]:
matrix[9:] # getting only last rows elements

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [22]:
matrix[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [24]:
matrix[:,0:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [28]:
matrix[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [30]:
matrix[7:10,5:7]

array([[76, 77],
       [86, 87],
       [96, 97]])

In [32]:
matrix[3:7, 3:6]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56],
       [64, 65, 66]])

In [33]:
matrix[3:7, 3:6].ndim

2

# Python Numpy Array Concatination and Split

# Concatenation

In [35]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [37]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [38]:
list1 = [2,4,6,7]
list2 = [1,8,3,5]
list1 + list2

[2, 4, 6, 7, 1, 8, 3, 5]

In [39]:
# list1 and list2 get conactenate using the + operator
# let me try the same thing on arr1 and arr2, and lets see what happen then,
arr1 + arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [40]:
# ooh by doing so (arr1 + arr2), we get the sum of the element of arr1 and arr2
# so + operator is no more concatenating two matrices
np.concatenate((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [41]:
# by default axis value in the concatenate function is 0, it means by default it will concatenate it by column
# lets concatenate it by row
np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [42]:
# we have also the vstack for vertical concatenating and hstack for horizontal concatenating
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [43]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [44]:
np.hstack((arr1, arr2, arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

# Split()

In [48]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
# splitting the arr1 in two parts and by default axis is 0, means it will split it by column,
# and it will return the list
np.split(arr1, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [47]:
np.split(arr1, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [50]:
# actually split funciton is returning the list and list is containing the array
# so lets print the element of that list
splitted_element_list = np.split(arr1, 2, axis=0)

In [51]:
print(splitted_element_list)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [52]:
print(splitted_element_list[0])

[[1 2 3 4]
 [5 6 7 8]]


In [55]:
print(type(splitted_element_list[0]))

<class 'numpy.ndarray'>


In [53]:
print(splitted_element_list[1])

[[ 9 10 11 12]
 [13 14 15 16]]


In [54]:
for item in splitted_element_list:
    print(item)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [58]:
# splitting  1 d array
arr1d = np.array([4,7,1,3,9])
print(arr1d)

[4 7 1 3 9]


In [59]:
np.split(arr1d, [1,3]) # i have pass one list inside it, [1,3]---> in array1 i want the element before 1 index, and in 
# array2 i want the element before 3 index and after starting from 1 index, and last array will contain the rest element,
# and it is also returning the list

[array([4]), array([7, 1]), array([3, 9])]

In [61]:
np.split(arr1d, [2,3]) #in array1 i want the element before 2 index which is 4,7 , and in 
# array2 i want the element before 3 index and after starting from 2 index which is 1, and last array will contain the 
# rest element

[array([4, 7]), array([1]), array([3, 9])]