In [1]:
import numpy as np

In [2]:
matrix_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
# by using numpy we can create the ones and zeroes matrix
matr_1s = np.ones((5))
print(matr_1s)
print(matr_1s.dtype)

[1. 1. 1. 1. 1.]
float64


In [14]:
# the value in this matrix is float type, so let me change it into integer
np.ones((9,3),'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
# in jupyter by clicking shift and tab on the function you can see what types and what are the parameters function is taking
mat1s = np.ones((5,6), dtype=int)
print(mat1s)
print(mat1s.dtype)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
int32


In [19]:
# now let me change this datatype into boolean value
mat1s = np.ones((4,5), dtype=bool)
print(mat1s)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [30]:
# zeroes matrix
mat0s = np.zeros((5,7), dtype = bool)
print(mat0s)
print(mat0s.dtype)

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]
bool


In [25]:
# we can also make this data type as string
mat0s = np.zeros((5,7), dtype=str)
print(mat0s)

[['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']]


In [29]:
print(mat0s.dtype)

<U1


In [49]:
# creating empty matrix
empty_matrix = np.empty((3,3))
print(empty_matrix)
# in empty matrix element can be any random value

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
